### ISSUE TITLE
Test `core::env::test::test_init_variables` failed

### ISSUE THREAD

**Issue by declantsien** [CeleritasCelery/rune#27]
```running 1 test
test core::env::test::test_init_variables ... FAILED

failures:

---- core::env::test::test_init_variables stdout ----
thread 'core::env::test::test_init_variables' panicked at 'called `Option::unwrap()` on a `None` value', /home/declan/src/Rust/rune/target/debug/build/rune-5da9fb7d4c9d8a64/out/sym.rs:656:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    core::env::test::test_init_variables

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 71 filtered out; finished in 0.00s
```
`rustc 1.71.1 (eb26296b5 2023-08-03)`

**Comment by CeleritasCelery** [comment]
Thanks for the bug report!

I am not able to reproduce the issue. Could you run with `RUST_BACKTRACE=1` and see if it gives a backtrace of where the unwrap is? Best I can see is it panicked when initializing the variable `load-path` but I don't see why that would happen.

**Comment by declantsien** [comment]
rune/target/debug/build/rune-5da9fb7d4c9d8a64/out/sym.rs:656:62
```   
 let bool_vars = env.vars.get_mut(sym::BYTE_BOOLEAN_VARS).unwrap();

**Comment by declantsien** [comment]
BTW, I am on Linux. Here is the full backtrace:
```
RUST_BACKTRACE=full cargo test core::env::test::test_init_variables
warning: /home/declan/src/Rust/rune/target/debug/build/rune-f6518d35e7fb52e3/out/sym.rs
    Finished test [unoptimized + debuginfo] target(s) in 0.19s
     Running unittests src/main.rs (target/debug/deps/rune-4e3c899c68dfc997)

running 1 test
test core::env::test::test_init_variables ... FAILED

failures:

---- core::env::test::test_init_variables stdout ----
thread 'core::env::test::test_init_variables' panicked at 'called `Option::unwrap()` on a `None` value', /home/declan/src/Rust/rune/target/debug/build/rune-f6518d35e7fb52e3/out/sym.rs:656:62
stack backtrace:
   0:     0x55cbdb382df1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdaa196410d9ee0b9
   1:     0x55cbdb3aed2f - core::fmt::write::h66b3c629f3d623e4
   2:     0x55cbdb37fb67 - std::io::Write::write_fmt::hc3b13ee21464b781
   3:     0x55cbdb382c05 - std::sys_common::backtrace::print::hca95c2d0055e42a2
   4:     0x55cbdb384893 - std::panicking::default_hook::{{closure}}::hc03c01c56bca600c
   5:     0x55cbdb3845b0 - std::panicking::default_hook::hb2cb5315b6634f1c
   6:     0x55cbdb1468b2 - test::test_main::{{closure}}::h767aa51a64937811
   7:     0x55cbdb384f8e - std::panicking::rust_panic_with_hook::h75cd912a39a34e8a
   8:     0x55cbdb384cd1 - std::panicking::begin_panic_handler::{{closure}}::h1498b46f7849e167
   9:     0x55cbdb383256 - std::sys_common::backtrace::__rust_end_short_backtrace::hd36a39b27b98086b
  10:     0x55cbdb384a62 - rust_begin_unwind
  11:     0x55cbdb028a03 - core::panicking::panic_fmt::h98ef273141454c23
  12:     0x55cbdb028a93 - core::panicking::panic::hf53fd8b0bfa5848e
  13:     0x55cbdb0be3f0 - core::option::Option<T>::unwrap::h39082109b612a5e7
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/option.rs:935:21
  14:     0x55cbdb0f548c - rune::core::env::init_variables::h8ffa460bdd55ada9
                               at /home/declan/src/Rust/rune/target/debug/build/rune-f6518d35e7fb52e3/out/sym.rs:656:21
  15:     0x55cbdb0c2160 - rune::core::env::test::test_init_variables::habb551e96d759250
                               at /home/declan/src/Rust/rune/src/core/env.rs:335:9
  16:     0x55cbdb0bd0a7 - rune::core::env::test::test_init_variables::{{closure}}::hb963d6cfc94d376b
                               at /home/declan/src/Rust/rune/src/core/env.rs:331:30
  17:     0x55cbdb055525 - core::ops::function::FnOnce::call_once::hc9a79451ea64ad80
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/ops/function.rs:250:5
  18:     0x55cbdb14bb6f - test::__rust_begin_short_backtrace::he4cc3c5ce81bf9ec
  19:     0x55cbdb14aaf7 - test::run_test::{{closure}}::h246159f43bf20b15
  20:     0x55cbdb1119bf - std::sys_common::backtrace::__rust_begin_short_backtrace::h018a394a06102b79
  21:     0x55cbdb1175af - core::ops::function::FnOnce::call_once{{vtable.shim}}::he0b95b6cda9e5fd4
  22:     0x55cbdb389495 - std::sys::unix::thread::Thread::new::thread_start::hcab660740b858b1f
  23:     0x7f2b8ccad3aa - start_thread
  24:     0x7f2b8cd2df7c - clone3
  25:                0x0 - <unknown>


failures:
    core::env::test::test_init_variables

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 71 filtered out; finished in 0.34s

error: test failed, to rerun pass `--bin rune`

**Comment by CeleritasCelery** [comment]
Thank you! So it looks like this was non-determinsim issue with the order of the files being parsed. I just happened to get lucky and never hit it.
